### ISSUE TITLE
Upgrade test on ubuntu 18.04 from 8.8.15 to 9.0.0

### ISSUE THREAD

**Issue by beezim-oss** [beezimOSS/beezoss#1]
Can someone test the upgrade of the official package of ubuntu 18.04 8.8.15 to the non official package here : 
http://www.beezim.fr/pages/zimbra-9-oss/

**Comment by adriangibanelbtactic** [comment]
Issue title says 8.8.15.
Issue body says 8.8.14.

Do you mean 8.8.15 and it's a typo?

Thank you.

**Comment by beezim-oss** [comment]
Yes, typo :) Fixed

**Comment by beezim-oss** [comment]
Upgrade working perfectly on ubuntu 18.04 from 8.8.15

**Comment by marshalleq** [comment]
Also tested an upgrade just today.  Worked perfectly.  A bit slower than I was expecting - but it's the first upgrade I've done of Zimbra.  For anyone else wondering how, just download the binaries at the link above and run install.sh to upgrade.
